version: "3.8"
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  node-app:
    build: .
    image: jocelynlam/dgu-extension
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - ../Database/mongodb-dgu-extension:/data/db
    command: [ --auth ]