name: DEPLOY EXTENSION PROJECT

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Code
        run: |
          npm ci
          npm run build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Build and Run Docker Compose
        run: |
          docker-compose -f docker-compose.yml build node-app

      - name: Push Docker image to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker push jocelynlam/dgu-extension        

  deploy:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.HOST_USERNAME }}
          TARGET: ${{ secrets.HOST_TARGET }}
          SCRIPT_AFTER: |
            cd app
            docker-compose -f docker-compose.yml pull node-app
            docker-compose -f docker-compose.yml -f docker-compose.pro.yml up -d
            docker image prune -af
            docker ps
            
            
            
