name: Hello World

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches:
      - 'main'

jobs:
  hello:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Print Hello World
        run: echo "Hello World"

      - name: Add .env file
        run: echo "${{ secrets.DEV_ENV }}" > .env

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm ci

      - name: Create Reports Directory
        run: mkdir -p reports
  
      - name: Run Tests and Capture Output
        run: npm test -- --reporters=default --reporters=jest-junit > reports/jest-junit.xml || true

      - name: View Test Results
        run: cat reports/jest-junit.xml

      - name: Comment PR with Test Results
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          comment_body="Issue"
          if [ -z "$comment_body" ]; then
            comment_body="No test results found."
          fi
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"body\":\"Test Results:\\n\`\`\`\\n${comment_body}\\n\`\`\`\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments"